// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FANR7K2-3B1RQ3z06Mrm_O-StSZoYEs',
    appId: '1:299558216837:web:fc71e91d003728666875ec',
    messagingSenderId: '299558216837',
    projectId: 'damkar-21ca7',
    authDomain: 'damkar-21ca7.firebaseapp.com',
    storageBucket: 'damkar-21ca7.firebasestorage.app',
    measurementId: 'G-LBTN0CL5MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kiIsxrJRpUiWRXOqI2UgFazBHSDvgtQ',
    appId: '1:299558216837:android:fba2291837454dce6875ec',
    messagingSenderId: '299558216837',
    projectId: 'damkar-21ca7',
    storageBucket: 'damkar-21ca7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-gyme0OE2VdmG2wBvQzg7Hzg3Cldj9g',
    appId: '1:299558216837:ios:6499dc50129ce0736875ec',
    messagingSenderId: '299558216837',
    projectId: 'damkar-21ca7',
    storageBucket: 'damkar-21ca7.firebasestorage.app',
    iosClientId: '299558216837-heeml4sqpf9d91d5uhceok6oo3e68qr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-gyme0OE2VdmG2wBvQzg7Hzg3Cldj9g',
    appId: '1:299558216837:ios:6499dc50129ce0736875ec',
    messagingSenderId: '299558216837',
    projectId: 'damkar-21ca7',
    storageBucket: 'damkar-21ca7.firebasestorage.app',
    iosClientId: '299558216837-heeml4sqpf9d91d5uhceok6oo3e68qr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3FANR7K2-3B1RQ3z06Mrm_O-StSZoYEs',
    appId: '1:299558216837:web:b78cef6a1b1a18796875ec',
    messagingSenderId: '299558216837',
    projectId: 'damkar-21ca7',
    authDomain: 'damkar-21ca7.firebaseapp.com',
    storageBucket: 'damkar-21ca7.firebasestorage.app',
    measurementId: 'G-VNDL3WWYF5',
  );

}